apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: nginx  # Match this label with your deployment's selector
  ports:
    - protocol: TCP
      port: 80  # Port on which the service will be exposed inside the cluster
      targetPort: 80  # Port on which your application is listening inside the pod
      nodePort: 30080  # Optional: Specify the nodePort if you want a specific port
